version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: azure/svelte
    container_name: azure-svelte
    ports:
      - "3010:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/static:/usr/src/app/static
    command: npm run dev -- --host --open
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: flask
    container_name: azure-flask
    ports:
      - "5001:5000"
    #volumes:
    #  - ./backend:/code
    #command: /bin/sh -c "python3 /code/main.py"
